## 19IT016 Manav Butani

# **Numpy**

In [1]:
import numpy as np

***Creating blank array***

In [2]:
array=np.empty(0, dtype=int)
print(array)

[]


***with predefined data***

In [3]:
array=np.ones(20)
print(array)

array=np.zeros(20)
print(array)

arr = np.array([1, 2, 3, 4, 5])
arr

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([1, 2, 3, 4, 5])

***with pattern specific data***

In [4]:
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [5]:
name = ['Manav', 'Raj', 'Krenil', 'Rut']
age = [19, 20, 61, 30]
weight = [65.0, 90.5, 64.0, 75.5]

In [6]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Manav', 19, 65. ) ('Raj', 20, 90.5) ('Krenil', 61, 64. )
 ('Rut', 30, 75.5)]


Slicing and Updating elements

In [7]:
slice_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
slice_array_1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [8]:
slice_array[7]=62
slice_array_1[0,3]=16
print(slice_array)
print(slice_array_1)

[ 1  2  3  4  5  6  7 62  9]
[[ 1  2  3 16  5]
 [ 6  7  8  9 10]]


In [9]:
print(slice_array[1:7])
print(slice_array[2:])
print(slice_array[:12])
print(slice_array[-3:-1])
print(slice_array[1:8:3])
print(slice_array_1[1, 1:4])

[2 3 4 5 6 7]
[ 3  4  5  6  7 62  9]
[ 1  2  3  4  5  6  7 62  9]
[ 7 62]
[ 2  5 62]
[7 8 9]


***Shape Manupalation***

In [10]:
array=np.arange(2,61,2).reshape(5,6)
array

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60]])

In [11]:
array=np.arange(2,61,2).reshape(10,3)
array

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54],
       [56, 58, 60]])

***Looping Over Array***

In [12]:
print("1-dimension Array")
for x in slice_array:
     print(x)

1-dimension Array
1
2
3
4
5
6
7
62
9


In [13]:
print("2-dimension Array")
for x in slice_array_1:
    for y in x:
        print(y)

2-dimension Array
1
2
3
16
5
6
7
8
9
10


*** Reading files in numpy***

In [14]:
import numpy as np
data = np.loadtxt("manav.txt", usecols=1, skiprows=1, dtype='str')
  
for each in data:
    print(each)

Manav
raj
Rut
jeel
Krenil
Rajan


# Use numpy vs list for matrix multiplication of 1000 X 1000 array


In [15]:
import time

start_time = time.time()

num_multiplies = 5000000
data = range(num_multiplies)
number = 1

for i in data:
    number *= 1.0000001

end_time = time.time()

print(number)
print("Run time = {}".format(end_time - start_time))

1.648721229963447
Run time = 0.4049561023712158


In [16]:
import time
import numpy as np

start_time = time.time()

data = np.ones(shape=(1000, 1000), dtype="float")

for i in range(5):
    data *= 1.0000001

end_time = time.time()

print("Run time = {}".format(end_time - start_time))

Run time = 0.008976459503173828
